# Generated by Django 4.2.7 on 2025-07-15 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('partner_type', models.CharField(choices=[('insurance', 'Insurance Company'), ('bank', 'Bank'), ('nbfc', 'NBFC'), ('fintech', 'Fintech Platform')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('api_secret', models.CharField(blank=True, max_length=128)),
                ('registration_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
