# Generated by Django 4.2.7 on 2025-07-15 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sensitivity_level', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Data categories',
                'db_table': 'data_categories',
            },
        ),
        migrations.CreateModel(
            name='DataSharingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.TextField()),
                ('purpose_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('requested_data_categories', models.ManyToManyField(to='consent.datacategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_sharing_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_duration_days', models.IntegerField(default=7)),
                ('max_access_count', models.IntegerField(default=10)),
                ('access_token', models.CharField(blank=True, max_length=128, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consented_data_categories', models.ManyToManyField(to='consent.datacategory')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consent.datasharingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_records',
            },
        ),
    ]
