# Generated by Django 4.2.7 on 2025-07-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consent', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('consent_requested', 'Consent Requested'), ('consent_granted', 'Consent Granted'), ('consent_denied', 'Consent Denied'), ('data_accessed', 'Data Accessed'), ('access_denied', 'Access Denied'), ('consent_revoked', 'Consent Revoked')], max_length=30)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.consentrecord')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
